logging:
  pattern:
    console: ''
spring:
  ai:
    mcp:
      server:
        version: 0.0.1
        name: mcp
  application:
    name: weather
  main:
    banner-mode: 'off'
    web-application-type: none
